# Generated by Django 5.1.3 on 2024-11-24 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Тел. Номер')),
                ('document_type', models.CharField(choices=[('referat', 'Реферат'), ('referat_handwritten', 'Реферат (от руки)'), ('consplect_lecture', 'Конспект, Лекция'), ('presentation', 'Презентация')], default='referat', max_length=50, verbose_name='Тип документа')),
                ('topic', models.CharField(max_length=255, verbose_name='Тема')),
                ('description', models.TextField(verbose_name='Описание')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Выполнен')),
                ('deadline', models.DateTimeField(blank=True, null=True, verbose_name='Срок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создание')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновление')),
            ],
        ),
    ]
